name: .NET Core CI

on: [push]

env:
  AZURE_WEBAPP_NAME: minimalweather20210428173256    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dotnet/MinimalWeather/publish'      # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
  CONFIGURATION: Release
  WORKING_DIRECTORY: dotnet/MinimalWeather
  DOTNET_CORE_VERSION: '6.0.x'           # set this to the dot net version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        include-prerelease: true
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}" -r linux-x64
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore -r linux-x64
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}" -r linux-x64
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
